apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-05T17:43:44Z"
  name: simplenode-canary
  resourceVersion: "990680"
  selfLink: /api/v1/namespaces/keptn05eks-prod/services/simplenode
  uid: d028cc25-fff3-11e9-b414-0ea8b065423c
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: simplenode
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
