apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-06T10:07:13Z"
  name: simplenode-primary
  resourceVersion: "1103581"
  selfLink: /api/v1/namespaces/keptn05eks-prod/services/simplenode
  uid: 34188b32-007d-11ea-b414-0ea8b065423c
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: simplenode-primary
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
