apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: simplenode
spec:
  gateways:
  - keptn05eks-staging-gateway.keptn05eks-staging
  - mesh
  hosts:
  - simplenode.keptn05eks-staging.keptn05-agrabner.demo.keptn.sh
  - simplenode
  - simplenode.keptn05eks-staging
  http:
  - route:
    - destination:
        host: simplenode.keptn05eks-staging.svc.cluster.local
